language: android

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "azGHU1vO6omrZk/0RvW1v6uQ9jhzpdZsAFNqO/DR/hLjRMS6Y+3NK5o7Q8onJE0qHSc5CeIR8/GMD+Lb3Vi1hUkk6Ya7QVUqgylkRmepdGzCNBnpq/Hpnv57CMvF7Jn0ON9p4llR9f05J3dMTYa6DbZMO5A+EpRmqsh60DCLPT4/tSwd6bxAJT11fgZeJ5Pk63M/VCnaBZ4yLK5qCj0v8MtBIZvkViHeN2sO5FXADzpAJ2YBo1EbOs0MpwaHlwgeHYUvkBMDfKWkSKkxmN6EiR1JqnqujYQ/eUkdTTRzzRcTDecFrqHMK4pTz+PDNK8E65wK+yS0SnO5OOHm2YQyZw0+mYexhQhClbFf7xtGxyn3aRGyXk9p8NWCbtjPKTUxlxJOk9BKglcU/6ABXITm5Q20vNN7MEbsWCAy06URV371Enhry8w/slH2qSnSnxfRXSyirllKLeBZjHy8QJ7KfijkWUWMuAHFPLBywfSkycKR3GlQNHpphA0R/6Ai8q6PQQB4N5FfuSyS8g/W+yUOXD3mopvBLGFgrC3TWzAJjjwXP4nTHTzeNSdFB4znYXpbge6siEm9EIG5ZtQfjbXAgomKuHdA9wgvZEMpKGclHITIHZCAZspr0rEwoRrTc9/+RKn4JjgqxwGt7b4SKCBCybxiBHKUbey7vOeVVpV8yqY="
    - secure: "fPTH/n+hDA0bHiCAr8e6iV34Wi1zrLxxzV5cd9pRXp7NGBCRzrk5zcRGUcPFxVWDXzUp6lZHYzSHFjBMmUcv9gp2c9IebDXNAaIqAlyjTioV99V2Rxr8aRMNqh1J4ICvhM00nTJZisKSeaiOIMzO7MA3JDcCWc5yq+TFOw0u+Vx2sPVGBUBQdFily8VSqvKqOgNYb9lc5WJYBM+1/yQqJSfqgTPsbp3LLreaZZRp/fEtF2Vh9VYH4Mv7wW0fb77pNmOp/0Flien+rhDvpv+tYBkDeqr2lGY22lCl2xN2nHFgjsusTi1fDg7bdjJAkgin2w55i8TpLMB7KjGwD7/lO0vEqQyg71TgkRrxiKuR35x8Tj7eGY5wqgFKsE9HqMvDdNjWGDvkJm0uKIV01ldiQw9zQaWKHTig9rYGWSoH/M8wSomgIBjfBk1nQeHKbymM0aPZrz1CmxYt/xOBGiPnlVPpYki1yuW0UT16uPhNRoPdDPDiY93QpxEkE+OmwNAIbhkzo+zwoG65d9z9TPE9OV8ogq8H0A6wggDMjtMnn+T8s++VppDaPZm+WYDfkWQSovZMztvHw8lpapM+IJEYeBT+3ZdzN+sWHajRh0Mj1O3cXnz5sjiob/wZ4i86FRJCx18NC6XyRGZ+D9co+irsd2xwgA4LXHECzp0hcQYf+8g="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

sudo: false