language: android

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "SXaCDXsgHbtsDoFNicxwkeyadLtJuVccdf3+taOwjlXxLdT1S0zsgvI8mFpfaRufp3wzRG2MznDuts5JquyA90JRHB3YUab+x4DOeQ+ZUjxtTb2m63YjwSjbYjxdgFgPALmK+iYNXiDZvxBRc0IH3fPkboiQWlEGGInu98fwGSm+iS23tGQEoqLPgBLUt8yQ7/EjX2wN2E1bHltYIOQ5C7Ny7vbilYRfUz5JGvqzenhoMCSq79HL0uEFlRITXkV4Hcop93bDoipQot9SUbp3ba7s22bAgcX9NvHOo1KPDsgr47qixlXKmALfZQdIHfaXWEEs1MlZbBy+5x0LwCnaK2L0klaqEkzbFk7Jg9QWfy1JsUGbjj/skOpr7xHg13LVWwkiL/G9LGjgCIy/oAIFcesEz44BhDWfRQq94noKmw+gxNKNfntXDCvKwoHu+QhJgiEPNDLE81s8hCuftM787ZfA3wW1+Dt7vjRMl/x/3qciDmxgiQrYuOxcGRyCz/R/pOq9xJrMNmauX4mae7NwDFqaEvAMvtDrtycGMJL/HUb6Fe3yQol0iJQizgX5kzV3gHU2cdvsUqc3hJm5zyaoojcjSAMVbe721ErOdVTCtciZ8Yd74y626R4uB/2QfqCaw/sUBoGjeviP/QeC3+/RE2paE4exlMDWmDp7aVyQXJI="
    - secure: "aBfRulEmq3XxLXKY5gvoXrsW0WYTt1s9jgwRr10yBRL9teErWCL29V+PfAo8/HJTCKGqob5zq8+MqyD2EAF+y3sqceXLCuzWSB68913iLlJNzG/JPE2zJjD0NAZ0RZmLJ79nXJRFcXynnKlG2DGkFdEIFOj+wqMpWtNVN1m4NE6bobi+iIc5hm9WqDhSBe1l2PSJ5kQNIHhNCXQinWTzJApcwEnDbMljZtrlRDWwy5eb35lDqH2W4+U9ZmJkadW0Qf4lc+0N+TvwHyMkwvORRr9QBsGnH0IJPg0iRBOGYj50xHgvXFowaXQTfg2oD27UBWxA01t8IEAAcAsOvgC5dRrAoOJaqXxUuF8w8CRFevaHc+ECxgmMwcauhM7oBfdHA3VcKbml5TYTrOSG+2/9f9akAN2YoBZBGSa6OgJ++CfdLTZbkWLTJcog8gZDTYBzTWFDk6dRflzNMPNgxub8o/DsMFeaDL/nl4cVAPhr3XwM31iwTo8nEy5sTw1wWmuAl1HuqC7AKQ6iG5i4gUXGgAkjoAGcYfc8nrGsdVNqBnnMum1HMAUiHg6/Z03VHfF93c+qFy0HVoFwvwNFk2DARDvWW52Ng8WXT8OG+NVkLoR+FCZwslrTXdOi4sX9D29xRk9z6UULtHCggT8230Zwn65BcTu3i99lUGqB+6zIuSs="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

sudo: false