language: android

jdk:
  - oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew clean check

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: "O7XmmVYdRE9V9eOusOexX3d8bg/mzcUaH8HTT9yv1yDe4oou/dJlcCpMU0SWQaOkEKZ7qmfkGqXFdojYsSs2rIVn96Tgs6RrZ8Leb8mKlslA99zTOHgMt6Ql9Oh0nD/Ari7pDM0LvjDc2dDPOGk0j95NIfLCEV10df07owcbZoUWCRH0YkzmA2Vihwdpba4RkqHPBa6QVsg7TrN7GOMAQ/lp3NXqbQfaVt7pufsAD+f1pcJJBKz9ErzZs2MJDkxxrx9XoAEwhc2n1hvDDFweTnw5gIqkhzeqouaB8rb8sRevi4kvLPeJSVanm9LjMpnkq0PIXkODt8yDfYrdLJtrFLOOk5vSb3h4T089EGK5B3alvoSQgd/6ai9J0vSkUQB1MyB7zN+j7HeAf3BnZzZdc7JF79oP0rKgPyxOhsWmtk+N90Uf1Nrx7GeGokrRQya0t05ZW8RLG6Gw1v1MgCZDaNKod3Aju9Z6g+ZYYqOEcPuLD09FX+Wub4oDbyXqZ/+HoRBu/fhV2/2mWfB1+7fS3j0lEsYPt+C+QlB7QLqlyegz9Mu5F4wi04jUl2yfxj4QrfQK7atG1jGAKWbehYY3ttKvrPql9+ube4fuVI4R0rmSw1GPWlYk/TUzA9m3V7+GRM/v1ZHTZhS1wjKPrEPDJN1tYpAglBGGiHBu4m6Ncvc="
  - secure: "oaD8M1ukbZsYGZ+MNpQWXp7TbqnVjkdfp3XwSyL6biihkVUdleWc5ooLssq9LZNWdlnbvM7iqTEX6w/buJKC0ZukWQWiHyPIyvPOqA1RcOtp9db7m4bCBz59/gmNtNfQYRgK7Ep75P4ePaWlamPZdb7/p3dQiIgCkC90/h4IcHuxJ3PSAbSX+kb1AUbRC90vT//pRJ9gaf2YgDVSgaz1bthU7AwamNyqKHM8ilrK2pTE6+A05Zl2jO/Ahc3zYz9JDakjY5Uk2pZ1F0K7KCEhzcbjMO2GlfIafvMXZB0b8tr55if04EsmiNfj7T5tc2HwU0UeXT6G5ft5JLZy0VrXFnwVLM87enV3SUEQuW2yJStgv/6LPK5MzEL55i0uFYkL/pZqVzoeRFKnxL/+n/kgpqUgUSYkwObfKpvx+ZUdZPtOcEwPzsjUJuL7x7PuLOaixW0PfIHnWgEksb+k4CgzSscOzc7HGCUL78nDC/ujcohG1K3yL/RoDf9qshxFP+EXAcq+xVEUQewNMkZJZPLwfyf6r2Fz1tyiD0dYONbLongeeT7RyTBRbCF8sA9CvAzT7V296FqO1Hw9y/UEQeICeTJ1DONyVM12M5efCyTpUGOLCTR42Ye5oBlQ0yjLlA5AzmuGvmUHTIJarBjhajm7dKRFoN4QGlo020mVOxGYWmA="

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

sudo: false